language: node_js
node_js:
  - "7"
before_script:
  - npm install -g grunt-cli
script:
  - grunt eslint
  - grunt mochaTest
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - maxime.beguin@veo-labs.com
    on_success: always
    on_failure: always
